AKIRONAKAHIGASHI/freemarket_sample0323_ver2

- app/assets/stylesheets/modules/banner.scss
- app/assets/stylesheets/modules/footer.scss
- app/assets/stylesheets/modules/header.scss
- app/assets/stylesheets/modules/index.scss
- app/views/items/_index.html.haml
- app/views/items/index.html.haml
- app/views/shared/_footer.html.haml
> edit_top_page

- app/assets/stylesheets/mixins/mixin.scss
> Change mixin.scss

- config/routes.rb
> add items routing

- app/assets/stylesheets/modules/item.scss
> fix_items_detail_page

- app/assets/stylesheets/buy/index.scss
- app/views/buy/_index.html.haml
> View.rechange

- app/assets/stylesheets/modules/sidebar.scss
WHAT
ビューの編集
WHY
他のビューに影響を与えていたため
> Side-bar.edit

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/purchase.scss
- app/views/buy/purchase.html.haml
> items_purchase_payjp

- app/assets/stylesheets/mixins/mixin.scss
- app/assets/stylesheets/modules/header.scss
- app/views/shared/_header.html.haml
headerのログイン時のビューを追加。
未ログイン、ログイン後の分岐を追加。
> edit_header

- app/assets/stylesheets/modules/item.scss
- app/controllers/items_controller.rb
商品詳細ページのユーザのその他の出品に、現在表示している商品を表示しないように変更。
> edit_product_details

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_sell_btn.scss
- app/assets/stylesheets/modules/footer.scss
- app/assets/stylesheets/modules/header.scss
- app/assets/stylesheets/modules/item.scss
- app/assets/stylesheets/modules/logout.scss
- app/assets/stylesheets/modules/show.scss
- app/controllers/application_controller.rb
- app/views/creditcards/index.html.haml
- app/views/creditcards/new.html.haml
- app/views/items/_index.html.haml
- app/views/items/show.html.haml
- app/views/shared/_footer.html.haml
- app/views/shared/_header.html.haml
- app/views/shared/_sell_btn.html.haml
- app/views/shared/_sidebar.html.haml
- app/views/users/logout.html.haml
- app/views/users/personalinfomation.html.haml
- app/views/users/profile.html.haml
- app/views/users/show.html.haml
ログインからログアウト実装完了による各パスの修正、追加
出品ボタンを部分テンプレートに切り分け
> edit_routing

- app/controllers/buy_controller.rb
- app/controllers/creditcards_controller.rb
- app/models/user.rb
- app/views/buy/_index.html.haml
- app/views/creditcards/index.html.haml
> creditcards purchase

- app/assets/stylesheets/modules/breadcrumb.scss
- app/views/items/show.html.haml
- app/views/layouts/application.html.haml
- app/views/shared/_header.html.haml
- app/views/users/show.html.haml
> edit_breadcrumbs

- app/assets/javascripts/item.js
- app/assets/javascripts/profit.js
- app/assets/stylesheets/modules/new.scss
- app/controllers/items_controller.rb
- config/routes.rb
> Exhibit.view

- app/assets/stylesheets/modules/index.scss
- app/assets/stylesheets/modules/item.scss
- app/controllers/buy_controller.rb
- app/views/items/show.html.haml
- app/views/shared/_items.html.haml
- db/migrate/20190602074353_change_datatype_salestatus_of_items.rb
- db/schema.rb
WHAT
購入された商品画像に「sold」ラベルを表示
購入済みのものは「売り切れ」表示
WHY
再購入を防ぐ為
> item purchase

- app/assets/javascripts/show.js
- app/assets/stylesheets/modules/item.scss
- app/assets/stylesheets/modules/show.scss
- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/_index.html.haml
- app/views/items/index.html.haml
- app/views/items/show.html.haml
- app/views/items/toppage/_chanel.html.haml
- app/views/items/toppage/_cosme.html.haml
- app/views/items/toppage/_kids.html.haml
- app/views/items/toppage/_ladies.html.haml
- app/views/items/toppage/_mens.html.haml
- app/views/items/toppage/_nike.html.haml
- app/views/items/toppage/_supreme.html.haml
- app/views/items/toppage/_vuitton.html.haml
- app/views/users/show.html.haml
- config/breadcrumbs.rb
商品詳細ページの修正
その他の出品がない場合はタイトルを表示させないように変更。
トップページのカテゴリー分け。
> edit_item_details

- app/views/items/show.html.haml
- db/migrate/20190602191332_change_data_item_condition_to_items.rb
- db/migrate/20190602194532_change_data_delivery_burden_to_items.rb
- db/migrate/20190602195033_change_data_delivery_method_to_items.rb
- db/migrate/20190602195228_change_data_delivery_date_to_items.rb
- db/schema.rb
> change_column_data

- app/assets/javascripts/image_upload.js
- app/controllers/items_controller.rb
- app/views/items/edit.html.haml
> exhibitEdit.page

- app/views/items/edit.html.haml
> Category tree.edit

- app/assets/stylesheets/modules/item.scss
- app/controllers/buy_controller.rb
- app/views/items/show.html.haml
> edit show item page

- app/models/item.rb
- app/validators/ng_word_validator.rb
- config/application.rb
銀テープ、会報、サイン、オリンピックチケットなど出品できないものを追加してみた
（エラーメッセージはまだ出ない）
> Validation.add
